export const GET_MOVIE_LIST = 'GET_MOVIE_LIST';
export const GET_MOVIE_LIST_SUCCESS = 'GET_MOVIE_LIST_SUCCESS';
export const GET_MOVIE_LIST_ERROR = 'GET_MOVIE_LIST_ERROR';

export const GET_MOVIE_SYNOPSIS = 'GET_MOVIE_SYNOPSIS';
export const GET_MOVIE_SYNOPSIS_SUCCESS = 'GET_MOVIE_SYNOPSIS_SUCCESS';
export const GET_MOVIE_SYNOPSIS_ERROR = 'GET_MOVIE_SYNOPSIS_ERROR';

export const GET_MOVIE_SEARCH = 'GET_MOVIE_SEARCH';
export const GET_MOVIE_SEARCH_SUCCESS = 'GET_MOVIE_SEARCH_SUCCESS';
export const GET_MOVIE_SEARCH_ERROR = 'GET_MOVIE_SEARCH_ERROR';